name: remote_painting
description: "University course project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/logo.png"
  ios: true
  windows:
    generate: true
  macos:
    generate: true

flutter:
  uses-material-design: true
